import { createInviteToken, verifyInviteToken } from './src/lib/invite.ts';
const token = createInviteToken('test@example.com', 'Employee');
console.log('Generated token:', token);
const encoded = encodeURIComponent(token);
console.log('URL encoded token:', encoded);
const decoded = decodeURIComponent(encoded);
console.log('URL decoded token:', decoded);
const payload = verifyInviteToken(token);
console.log('Payload:', payload);
const payloadFromDecoded = verifyInviteToken(decoded);
console.log('Payload from decoded:', payloadFromDecoded);
